"""
Comprehensive Grammar Knowledge Base, Slang & Profanity Dictionaries,
and Sentence Pattern Pools for LocalDictionary Syntax Engine.
"""

# ==============================================================================
# 1. BILINGUAL SLANG & PROFANITY DICTIONARIES (EN ⇄ TR)
# ==============================================================================

# Multi-word idioms and colloquial phrases (EN -> TR)
SLANG_IDIOMS_EN_TR = {
    "what the fuck": {"slang": "bu da ne amk", "clean": "bu da ne böyle"},
    "what the hell": {"slang": "ne oluyor lan", "clean": "ne oluyor böyle"},
    "what the heck": {"slang": "ne oluyor yahu", "clean": "ne oluyor"},
    "shut the fuck up": {"slang": "çeneni siktiğimin kapa", "clean": "kapa çeneni"},
    "shut your mouth": {"slang": "kapa o çeneni", "clean": "sessiz ol"},
    "shut up": {"slang": "kapa çeneni", "clean": "sus"},
    "get the fuck out": {"slang": "siktir git", "clean": "derhal defol"},
    "fuck off": {"slang": "siktir git", "clean": "defol git"},
    "fuck you": {"slang": "siktir git", "clean": "canın cehenneme"},
    "holy shit": {"slang": "hasiktir", "clean": "aman tanrım"},
    "piece of shit": {"slang": "bok parçası", "clean": "pislik herif"},
    "son of a bitch": {"slang": "orospu çocuğu", "clean": "it oğlu it"},
    "cut the crap": {"slang": "boş yapmayı kes", "clean": "zırvalamayı bırak"},
    "bullshit": {"slang": "saçmalık", "clean": "palavra"},
    "damn it": {"slang": "kahretsin", "clean": "lanet olsun"},
    "piss off": {"slang": "defol git", "clean": "toz ol"},
    "pissed off": {"slang": "tepesi atmış", "clean": "çok sinirli"},
    "screw you": {"slang": "canın cehenneme", "clean": "cehenneme git"},
    "screw up": {"slang": "sıçıp batırmak", "clean": "berbat etmek"},
    "calm the fuck down": {"slang": "sakinleş amk", "clean": "sakin ol"},
    "chill out": {"slang": "rahatla", "clean": "sakinleş"},
    "hang out": {"slang": "takılmak", "clean": "vakit geçirmek"},
    "don't give a fuck": {"slang": "zerre sikimde değil", "clean": "zerre umrumda değil"},
    "don't give a shit": {"slang": "zerre sikimde değil", "clean": "zerre umrumda değil"},
    "no cap": {"slang": "harbi yalan yok", "clean": "gerçekten"},
    "bite me": {"slang": "çok da umrumda", "clean": "hadi ordan"},
    "drop dead": {"slang": "geber", "clean": "yok ol"},
    "kiss my ass": {"slang": "kıçımı ye", "clean": "nah sana"},
    "go to hell": {"slang": "cehennemin dibine git", "clean": "cehenneme git"},
    "who the fuck": {"slang": "kim ulan", "clean": "kim bu"},
    "why the fuck": {"slang": "neden amk", "clean": "neden böyle"},
    "how the fuck": {"slang": "nasıl lan", "clean": "nasıl olur"},
    "where the fuck": {"slang": "nerede lan", "clean": "nerede"}
}

# Multi-word idioms and colloquial phrases (TR -> EN)
SLANG_IDIOMS_TR_EN = {
    "siktir git": {"slang": "get the fuck out", "clean": "get out of here"},
    "siktir ol git": {"slang": "fuck off and leave", "clean": "get out of here"},
    "siktir": {"slang": "fuck", "clean": "damn"},
    "siktir lan": {"slang": "fuck off", "clean": "get lost"},
    "hasiktir": {"slang": "holy shit", "clean": "damn it"},
    "sikeyim seni": {"slang": "fuck you", "clean": "to hell with you"},
    "seni sikeyim": {"slang": "fuck you", "clean": "to hell with you"},
    "sikeyim": {"slang": "fuck it", "clean": "damn it"},
    "sikik": {"slang": "fucked up", "clean": "messed up"},
    "sikikler": {"slang": "motherfuckers", "clean": "jerks"},
    "ananı sikeyim": {"slang": "motherfucker", "clean": "damn it"},
    "amına koyayım": {"slang": "fuck it / for fuck's sake", "clean": "damn it"},
    "amına koyim": {"slang": "fuck it", "clean": "damn it"},
    "sikimde değil": {"slang": "I don't give a fuck", "clean": "I don't care"},
    "benimle denk değilsin": {"slang": "you are no match for me", "clean": "you are not my equal"},
    "denk değilsin": {"slang": "you are no match", "clean": "you are not equal"},
    "beni kimse yenemez": {"slang": "nobody can beat me", "clean": "no one can defeat me"},
    "amk": {"slang": "wtf", "clean": "damn"},
    "aq": {"slang": "wtf", "clean": "damn"},
    "lanet olsun": {"slang": "damn it", "clean": "curse it"},
    "kahretsin": {"slang": "damn it", "clean": "blast it"},
    "boş yapma": {"slang": "cut the crap", "clean": "stop talking nonsense"},
    "kafayı yemek": {"slang": "freak out", "clean": "lose one's mind"},
    "kafayı yemiş": {"slang": "crazy as fuck", "clean": "out of one's mind"},
    "salla": {"slang": "forget about it", "clean": "brush it off"},
    "çuvallamak": {"slang": "screw up", "clean": "mess up"},
    "boka sarmak": {"slang": "go to shit", "clean": "fall apart"},
    "sıçıp batırmak": {"slang": "fuck up completely", "clean": "ruin everything"}
}

# Single slang & profanity tokens (EN -> TR)
SLANG_WORDS_EN_TR = {
    "fuck": {"slang": "sikmek", "clean": "kahretmek"},
    "fucking": {"slang": "amına koyduğumun", "clean": "lanet olası"},
    "shit": {"slang": "bok", "clean": "pislik"},
    "bitch": {"slang": "orospu", "clean": "kaltak"},
    "asshole": {"slang": "göt lalesi", "clean": "pislik herif"},
    "bastard": {"slang": "piç", "clean": "alçak"},
    "dick": {"slang": "sik", "clean": "hıyar"},
    "dickhead": {"slang": "sik kafalı", "clean": "hıyar"},
    "cunt": {"slang": "amcık", "clean": "pislik"},
    "dumbass": {"slang": "geri zekalı", "clean": "dangalak"},
    "badass": {"slang": "taşaklı", "clean": "havalı"},
    "motherfucker": {"slang": "orospu çocuğu", "clean": "alçak herif"},
    "crap": {"slang": "boktan", "clean": "berbat"},
    "freaking": {"slang": "lanet", "clean": "acayip"},
    "loser": {"slang": "ezik", "clean": "zavallı"},
    "noob": {"slang": "çaylak", "clean": "acemi"},
    "dude": {"slang": "moruk", "clean": "dostum"},
    "bro": {"slang": "kanka", "clean": "birader"},
    "homie": {"slang": "kanka", "clean": "arkadaş"},
    "sucks": {"slang": "berbat", "clean": "rezalet"}
}

# Single slang & profanity tokens (TR -> EN)
SLANG_WORDS_TR_EN = {
    "lan": {"slang": "man / dude", "clean": "hey"},
    "yavşak": {"slang": "asshole", "clean": "jerk"},
    "piç": {"slang": "bastard", "clean": "rascal"},
    "orospu": {"slang": "bitch", "clean": "vile person"},
    "mal": {"slang": "dumbass", "clean": "fool"},
    "hıyar": {"slang": "jerk", "clean": "boor"},
    "dingil": {"slang": "dimwit", "clean": "fool"},
    "dangalak": {"slang": "blockhead", "clean": "fool"},
    "kanka": {"slang": "bro", "clean": "friend"},
    "moruk": {"slang": "dude", "clean": "old pal"},
    "boktan": {"slang": "shitty", "clean": "awful"},
    "çakma": {"slang": "knockoff", "clean": "fake"}
}

# Turkish Copula Negation (değil çekimleri)
TURKISH_COPULA_NEGATION = {
    "değilim": {"en": "am not", "person": "1s"},
    "değilsin": {"en": "are not", "person": "2s"},
    "değil": {"en": "is not", "person": "3s"},
    "değiliz": {"en": "are not", "person": "1p"},
    "değilsiniz": {"en": "are not", "person": "2p"},
    "değiller": {"en": "are not", "person": "3p"},
    "değildim": {"en": "was not", "person": "1s"},
    "değildin": {"en": "were not", "person": "2s"},
    "değildi": {"en": "was not", "person": "3s"},
    "değildik": {"en": "were not", "person": "1p"},
    "değildiniz": {"en": "were not", "person": "2p"},
    "değillerdi": {"en": "were not", "person": "3p"}
}


# ==============================================================================
# 2. EXTENDED GRAMMATICAL VOCABULARY POOLS
# ==============================================================================

# Additional high-frequency English verbs mapped to Turkish infinitives
EXTENDED_VERBS_EN_TR = {
    "accept": "kabul etmek",
    "achieve": "başarmak",
    "admit": "itiraf etmek",
    "affect": "etkilemek",
    "afford": "karşılayabilmek",
    "agree": "katılmak",
    "allow": "izin vermek",
    "appear": "görünmek",
    "apply": "başvurmak",
    "argue": "tartışmak",
    "arrive": "varmak",
    "attack": "saldırmak",
    "avoid": "kaçınmak",
    "become": "olmak",
    "belong": "ait olmak",
    "bite": "ısırmak",
    "bleed": "kanamak",
    "breathe": "nefes almak",
    "burn": "yanmak",
    "care": "önemsemek",
    "carry": "taşımak",
    "catch": "yakalamak",
    "cause": "neden olmak",
    "choose": "seçmek",
    "clean": "temizlemek",
    "climb": "tırmanmak",
    "collect": "toplamak",
    "complain": "şikayet etmek",
    "complete": "tamamlamak",
    "confirm": "onaylamak",
    "connect": "bağlanmak",
    "consider": "düşünmek",
    "contain": "içermek",
    "continue": "devam etmek",
    "control": "kontrol etmek",
    "cook": "pişirmek",
    "count": "saymak",
    "cover": "örtmek",
    "cry": "ağlamak",
    "cut": "kesmek",
    "damage": "zarar vermek",
    "dance": "dans etmek",
    "deal": "uğraşmak",
    "decide": "karar vermek",
    "defend": "savunmak",
    "deliver": "teslim etmek",
    "demand": "talep etmek",
    "depend": "bağlı olmak",
    "describe": "tanımlamak",
    "destroy": "yıkmak",
    "develop": "geliştirmek",
    "disappear": "kaybolmak",
    "discover": "keşfetmek",
    "discuss": "tartışmak",
    "divide": "bölmek",
    "doubt": "şüphelenmek",
    "draw": "çizmek",
    "dream": "rüya görmek",
    "drop": "düşürmek",
    "earn": "kazanmak",
    "encourage": "cesaretlendirmek",
    "enjoy": "keyif almak",
    "enter": "girmek",
    "escape": "kaçmak",
    "examine": "incelemek",
    "exist": "var olmak",
    "expect": "beklemek",
    "explain": "açıklamak",
    "express": "ifade etmek",
    "fall": "düşmek",
    "feed": "beslemek",
    "fight": "savaşmak",
    "fill": "doldurmak",
    "fix": "onarmak",
    "focus": "odaklanmak",
    "forbid": "yasaklamak",
    "forgive": "affetmek",
    "freeze": "donmak",
    "gain": "kazanmak",
    "gather": "toplamak",
    "grow": "büyümek",
    "guess": "tahmin etmek",
    "hang": "asmak",
    "happen": "olmak",
    "hate": "nefret etmek",
    "hide": "saklamak",
    "hit": "vurmak",
    "hold": "tutmak",
    "hope": "umut etmek",
    "hurt": "incitmek",
    "identify": "tanımlamak",
    "ignore": "görmezden gelmek",
    "imagine": "hayal etmek",
    "improve": "geliştirmek",
    "include": "içermek",
    "inform": "bilgilendirmek",
    "injure": "yaralamak",
    "insist": "ısrar etmek",
    "invite": "davet etmek",
    "join": "katılmak",
    "jump": "zıplamak",
    "keep": "tutmak",
    "kick": "tekmelemek",
    "kiss": "öpmek",
    "knock": "çalmak",
    "laugh": "gülmek",
    "lead": "yönetmek",
    "lend": "ödünç vermek",
    "let": "izin vermek",
    "lie": "yalan söylemek",
    "lift": "kaldırmak",
    "light": "yakmak",
    "lock": "kilitlemek",
    "manage": "yönetmek",
    "marry": "evlenmek",
    "matter": "önem taşımak",
    "mean": "anlamına gelmek",
    "mention": "bahsetmek",
    "mind": "aldırmak",
    "miss": "özlemek",
    "move": "hareket etmek",
    "notice": "fark etmek",
    "obtain": "edinmek",
    "occur": "meydana gelmek",
    "offer": "teklif etmek",
    "order": "sipariş etmek",
    "organize": "düzenlemek",
    "pass": "geçmek",
    "perform": "sergilemek",
    "permit": "izin vermek",
    "place": "yerleştirmek",
    "point": "işaret etmek",
    "prefer": "tercih etmek",
    "prepare": "hazırlamak",
    "press": "basmak",
    "pretend": "numara yapmak",
    "prevent": "önlemek",
    "produce": "üretmek",
    "promise": "söz vermek",
    "propose": "önermek",
    "protect": "korumak",
    "prove": "kanıtlamak",
    "provide": "sağlamak",
    "pull": "çekmek",
    "push": "itmek",
    "reach": "ulaşmak",
    "realize": "farkına varmak",
    "receive": "almak",
    "recognize": "tanımak",
    "recommend": "önermek",
    "record": "kaydetmek",
    "refuse": "reddetmek",
    "regret": "pişman olmak",
    "remain": "kalmak",
    "remind": "hatırlatmak",
    "repair": "onarmak",
    "repeat": "tekrarlamak",
    "replace": "değiştirmek",
    "reply": "yanıtlamak",
    "report": "bildirmek",
    "request": "rica etmek",
    "require": "gerektirmek",
    "rescue": "kurtarmak",
    "resist": "direnmek",
    "respond": "yanıt vermek",
    "rest": "dinlenmek",
    "return": "dönmek",
    "reveal": "ortaya çıkarmak",
    "ring": "çalmak",
    "rise": "yükselmek",
    "risk": "riske atmak",
    "rob": "soymak",
    "roll": "yuvarlanmak",
    "save": "kurtarmak",
    "scream": "çığlık atmak",
    "search": "aramak",
    "seem": "görünmek",
    "select": "seçmek",
    "separate": "ayırmak",
    "serve": "hizmet etmek",
    "set": "ayarlamak",
    "settle": "yerleşmek",
    "shake": "sallamak",
    "share": "paylaşmak",
    "shine": "parlamak",
    "shoot": "ateş etmek",
    "shout": "bağırmak",
    "show": "göstermek",
    "shut": "kapatmak",
    "sign": "imzalamak",
    "sing": "şarkı söylemek",
    "sink": "batmak",
    "smile": "gülümsemek",
    "smoke": "sigara içmek",
    "solve": "çözmek",
    "spend": "harcamak",
    "spill": "dökmek",
    "steal": "çalmak",
    "struggle": "mücadele etmek",
    "study": "ders çalışmak",
    "succeed": "başarmak",
    "suffer": "acı çekmek",
    "suggest": "önermek",
    "suit": "uymak",
    "support": "desteklemek",
    "suppose": "varsaymak",
    "surprise": "şaşırtmak",
    "survive": "hayatta kalmak",
    "suspect": "şüphelenmek",
    "swear": "küfür etmek",
    "swim": "yüzmek",
    "taste": "tatmak",
    "tear": "yırtmak",
    "test": "test etmek",
    "thank": "teşekkür etmek",
    "throw": "fırlatmak",
    "tie": "bağlamak",
    "touch": "dokunmak",
    "train": "eğitmek",
    "travel": "seyahat etmek",
    "treat": "davranmak",
    "trust": "güvenmek",
    "turn": "dönmek",
    "use": "kullanmak",
    "value": "değer vermek",
    "vanish": "yok olmak",
    "visit": "ziyaret etmek",
    "vote": "oy vermek",
    "wait": "beklemek",
    "wake": "uyanmak",
    "warn": "uyarmak",
    "wash": "yıkanmak",
    "waste": "israf etmek",
    "wave": "el sallamak",
    "wear": "giymek",
    "weigh": "tartmak",
    "welcome": "karşılamak",
    "whisper": "fısıldamak",
    "win": "kazanmak",
    "wish": "dilemek",
    "wonder": "merak etmek",
    "worry": "endişelenmek",
    "yell": "bağırmak"
}

# Additional high-frequency English nouns mapped to Turkish
EXTENDED_NOUNS_EN_TR = {
    "accident": "kaza",
    "action": "eylem",
    "activity": "etkinlik",
    "actor": "aktör",
    "address": "adres",
    "advice": "tavsiye",
    "age": "yaş",
    "airport": "havalimanı",
    "alarm": "alarm",
    "alcohol": "alkol",
    "ambulance": "cankurtaran",
    "amount": "miktar",
    "apartment": "daire",
    "apple": "elma",
    "area": "alan",
    "arm": "kol",
    "army": "ordu",
    "art": "sanat",
    "artist": "sanatçı",
    "article": "makale",
    "attack": "saldırı",
    "attention": "dikkat",
    "author": "yazar",
    "baby": "bebek",
    "back": "sırt",
    "bag": "çanta",
    "ball": "top",
    "bank": "banka",
    "bar": "bar",
    "bathroom": "banyo",
    "beach": "kumsal",
    "bear": "ayı",
    "beauty": "güzellik",
    "bed": "yatak",
    "bedroom": "yatak odası",
    "beer": "bira",
    "beginning": "başlangıç",
    "behavior": "davranış",
    "bell": "zil",
    "bicycle": "bisiklet",
    "bird": "kuş",
    "birth": "doğum",
    "birthday": "doğum günü",
    "blood": "kan",
    "boat": "tekne",
    "body": "vücut",
    "bone": "kemik",
    "bottle": "şişe",
    "bottom": "dip",
    "box": "kutu",
    "brain": "beyin",
    "bread": "ekmek",
    "bridge": "köprü",
    "brother": "erkek kardeş",
    "building": "bina",
    "bus": "otobüs",
    "business": "iş",
    "butter": "tereyağı",
    "button": "düğme",
    "camera": "kamera",
    "camp": "kamp",
    "cancer": "kanser",
    "captain": "kaptan",
    "card": "kart",
    "care": "bakım",
    "career": "kariyer",
    "carpet": "halı",
    "castle": "kale",
    "cat": "kedi",
    "ceiling": "tavan",
    "celebration": "kutlama",
    "cell": "hücre",
    "century": "yüzyıl",
    "chain": "zincir",
    "chair": "sandalye",
    "champion": "şampiyon",
    "chance": "şans",
    "change": "değişiklik",
    "character": "karakter",
    "cheese": "peynir",
    "chicken": "tavuk",
    "choice": "seçim",
    "church": "kilise",
    "cinema": "sinema",
    "circle": "çember",
    "citizen": "vatandaş",
    "class": "sınıf",
    "classroom": "derslik",
    "climate": "iklim",
    "clock": "saat",
    "clothes": "giysiler",
    "cloud": "bulut",
    "club": "kulüp",
    "coast": "sahil",
    "coat": "palto",
    "coffee": "kahve",
    "coin": "madeni para",
    "colleague": "meslektaş",
    "college": "kolej",
    "color": "renk",
    "company": "şirket",
    "competition": "yarışma",
    "complaint": "şikayet",
    "concert": "konser",
    "condition": "koşul",
    "connection": "bağlantı",
    "conversation": "konuşma",
    "cook": "aşçı",
    "corner": "köşe",
    "cost": "maliyet",
    "country": "ülke",
    "courage": "cesaret",
    "court": "mahkeme",
    "cow": "inek",
    "crime": "suç",
    "crowd": "kalabalık",
    "culture": "kültür",
    "cup": "fincan",
    "customer": "müşteri",
    "damage": "zarar",
    "danger": "tehlike",
    "darkness": "karanlık",
    "daughter": "kız evlat",
    "death": "ölüm",
    "decision": "karar",
    "dentist": "diş hekimi",
    "department": "bölüm",
    "desk": "çalışma masası",
    "dessert": "tatlı",
    "destination": "varış noktası",
    "detail": "ayrıntı",
    "device": "cihaz",
    "dictionary": "sözlük",
    "dinner": "akşam yemeği",
    "direction": "yön",
    "director": "yönetmen",
    "dirt": "kir",
    "disaster": "felaket",
    "discipline": "disiplin",
    "disease": "hastalık",
    "dish": "yemek",
    "distance": "mesafe",
    "district": "ilçe",
    "document": "belge",
    "dog": "köpek",
    "dollar": "dolar",
    "door": "kapı",
    "dream": "rüya",
    "dress": "elbise",
    "driver": "şoför",
    "drug": "ilaç",
    "dust": "toz",
    "duty": "görev",
    "ear": "kulak",
    "earth": "dünya",
    "earthquake": "deprem",
    "economy": "ekonomi",
    "education": "eğitim",
    "effect": "etki",
    "effort": "çaba",
    "egg": "yumurta",
    "election": "seçim",
    "electricity": "elektrik",
    "element": "öğe",
    "emergency": "acil durum",
    "emotion": "duygu",
    "employee": "çalışan",
    "employer": "işveren",
    "employment": "istihdam",
    "end": "son",
    "energy": "enerji",
    "engine": "motor",
    "engineer": "mühendis",
    "environment": "çevre",
    "equipment": "ekipman",
    "error": "hata",
    "event": "olay",
    "evidence": "kanıt",
    "exam": "sınav",
    "example": "örnek",
    "excitement": "heyecan",
    "exercise": "egzersiz",
    "experience": "deneyim",
    "expert": "uzman",
    "explanation": "açıklama",
    "eye": "göz",
    "face": "yüz",
    "fact": "gerçek",
    "factory": "fabrika",
    "failure": "başarısızlık",
    "fair": "fuar",
    "faith": "inanç",
    "family": "aile",
    "farm": "çiftlik",
    "farmer": "çiftçi",
    "fashion": "moda",
    "fear": "korku",
    "feature": "özellik",
    "fee": "ücret",
    "feeling": "his",
    "field": "tarla",
    "fight": "kavga",
    "figure": "rakam",
    "film": "film",
    "finger": "parmak",
    "fire": "ateş",
    "fish": "balık",
    "flight": "uçuş",
    "floor": "zemin",
    "flower": "çiçek",
    "fog": "sis",
    "food": "yemek",
    "foot": "ayak",
    "force": "kuvvet",
    "forest": "orman",
    "fork": "çatal",
    "freedom": "özgürlük",
    "friend": "arkadaş",
    "friendship": "dostluk",
    "fruit": "meyve",
    "future": "gelecek",
    "game": "oyun",
    "garden": "bahçe",
    "garlic": "sarımsak",
    "gas": "gaz",
    "gate": "kapı",
    "generation": "nesil",
    "gift": "hediye",
    "glass": "bardak",
    "goal": "hedef",
    "gold": "altın",
    "government": "hükümet",
    "grass": "çimen",
    "ground": "yer",
    "group": "grup",
    "guard": "koruma",
    "guest": "konuk",
    "guide": "rehber",
    "gun": "silah",
    "hair": "saç",
    "half": "yarım",
    "hall": "salon",
    "hand": "el",
    "happiness": "mutluluk",
    "hate": "nefret",
    "head": "baş",
    "health": "sağlık",
    "heart": "kalp",
    "heat": "sıcaklık",
    "heaven": "cennet",
    "height": "boy",
    "hell": "cehennem",
    "hero": "kahraman",
    "hill": "tepe",
    "history": "tarih",
    "hobby": "hobi",
    "holiday": "tatil",
    "home": "ev",
    "homework": "ev ödevi",
    "honey": "bal",
    "hope": "umut",
    "horse": "at",
    "hospital": "hastane",
    "hotel": "otel",
    "hour": "saat",
    "house": "ev",
    "human": "insan",
    "hunger": "açlık",
    "husband": "koca",
    "ice": "buz",
    "idea": "fikir",
    "identity": "kimlik",
    "illness": "hastalık",
    "image": "görüntü",
    "imagination": "hayal gücü",
    "importance": "önem",
    "industry": "sanayi",
    "information": "bilgi",
    "injury": "yaralanma",
    "insect": "böcek",
    "inside": "iç",
    "instrument": "enstrüman",
    "insurance": "sigorta",
    "intention": "niyet",
    "interest": "ilgi",
    "interview": "mülakat",
    "invitation": "davet",
    "iron": "demir",
    "island": "ada",
    "issue": "konu",
    "item": "madde",
    "jacket": "ceket",
    "jam": "reçel",
    "jewel": "mücevher",
    "job": "iş",
    "joke": "şaka",
    "journey": "yolculuk",
    "judge": "yargıç",
    "juice": "meyve suyu",
    "justice": "adalet",
    "key": "anahtar",
    "kid": "çocuk",
    "king": "kral",
    "kitchen": "mutfak",
    "knee": "diz",
    "knife": "bıçak",
    "knowledge": "bilgi",
    "lake": "göl",
    "lamp": "lamba",
    "land": "kara",
    "language": "dil",
    "law": "kanun",
    "lawyer": "avukat",
    "leader": "lider",
    "leadership": "liderlik",
    "leaf": "yaprak",
    "lecture": "ders",
    "leg": "bacak",
    "lemon": "limon",
    "lesson": "ders",
    "letter": "mektup",
    "liberty": "hürriyet",
    "library": "kütüphane",
    "lie": "yalan",
    "life": "hayat",
    "light": "ışık",
    "line": "çizgi",
    "lion": "aslan",
    "lip": "dudak",
    "list": "liste",
    "literature": "edebiyat",
    "location": "konum",
    "lock": "kilit",
    "loss": "kayıp",
    "love": "aşk",
    "luck": "şans",
    "lunch": "öğle yemeği",
    "machine": "makine",
    "magazine": "dergi",
    "mail": "posta",
    "majority": "çoğunluk",
    "mall": "alışveriş merkezi",
    "man": "adam",
    "manager": "müdür",
    "map": "harita",
    "mark": "işaret",
    "market": "pazar",
    "marriage": "evlilik",
    "material": "malzeme",
    "math": "matematik",
    "meal": "öğün",
    "meaning": "anlam",
    "meat": "et",
    "medicine": "ilaç",
    "meeting": "toplantı",
    "member": "üye",
    "memory": "hafıza",
    "menu": "menü",
    "message": "mesaj",
    "metal": "metal",
    "method": "yöntem",
    "middle": "orta",
    "milk": "süt",
    "mind": "zihin",
    "minute": "dakika",
    "mirror": "ayna",
    "mistake": "hata",
    "moment": "an",
    "money": "para",
    "monkey": "maymun",
    "month": "ay",
    "mood": "ruh hali",
    "moon": "ay",
    "morning": "sabah",
    "mother": "anne",
    "mountain": "dağ",
    "mouse": "fare",
    "mouth": "ağız",
    "movie": "film",
    "museum": "müze",
    "music": "müzik",
    "musician": "müzisyen",
    "name": "isim",
    "nation": "ulus",
    "nature": "doğa",
    "neck": "boyun",
    "need": "ihtiyaç",
    "neighbor": "komşu",
    "nephew": "erkek yeğen",
    "news": "haber",
    "newspaper": "gazete",
    "niece": "kız yeğen",
    "night": "gece",
    "noise": "gürültü",
    "noon": "öğle vakti",
    "nose": "burun",
    "note": "not",
    "notebook": "defter",
    "number": "numara",
    "nurse": "hemşire",
    "ocean": "okyanus",
    "office": "ofis",
    "officer": "memur",
    "oil": "yağ",
    "operation": "operasyon",
    "opinion": "görüş",
    "opportunity": "fırsat",
    "option": "seçenek",
    "order": "düzen",
    "organization": "kuruluş",
    "owner": "sahip",
    "page": "sayfa",
    "pain": "acı",
    "paint": "boya",
    "painter": "ressam",
    "painting": "tablo",
    "pair": "çift",
    "palace": "saray",
    "pan": "tava",
    "paper": "kağıt",
    "parent": "ebeveyn",
    "park": "park",
    "part": "parça",
    "partner": "ortak",
    "party": "parti",
    "passenger": "yolcu",
    "passport": "pasaport",
    "path": "patika",
    "patient": "hasta",
    "payment": "ödeme",
    "peace": "barış",
    "pen": "kalem",
    "pencil": "kurşun kalem",
    "people": "insanlar",
    "pepper": "biber",
    "period": "dönem",
    "permission": "izin",
    "person": "kişi",
    "personality": "kişilik",
    "pet": "evcil hayvan",
    "pharmacy": "eczane",
    "phone": "telefon",
    "photo": "fotoğraf",
    "phrase": "ifade",
    "picture": "resim",
    "piece": "parça",
    "pig": "domuz",
    "pilot": "pilot",
    "pipe": "boru",
    "place": "yer",
    "plan": "plan",
    "plane": "uçak",
    "planet": "gezegen",
    "plant": "bitki",
    "plastic": "plastik",
    "plate": "tabak",
    "player": "oyuncu",
    "pocket": "cep",
    "poem": "şiir",
    "poet": "şair",
    "point": "nokta",
    "poison": "zehir",
    "police": "polis",
    "policy": "politika",
    "pool": "havuz",
    "population": "nüfus",
    "position": "konum",
    "post": "posta",
    "pot": "tencere",
    "potato": "patates",
    "power": "güç",
    "practice": "pratik",
    "prayer": "dua",
    "president": "cumhurbaşkanı",
    "price": "fiyat",
    "priest": "rahip",
    "prince": "prens",
    "princess": "prenses",
    "prison": "hapishane",
    "prisoner": "mahkum",
    "problem": "sorun",
    "product": "ürün",
    "production": "üretim",
    "profession": "meslek",
    "professor": "profesör",
    "program": "program",
    "progress": "ilerleme",
    "project": "proje",
    "promise": "söz",
    "property": "mülk",
    "protection": "koruma",
    "pupil": "öğrenci",
    "purpose": "amaç",
    "queen": "kraliçe",
    "question": "soru",
    "rabbit": "tavşan",
    "race": "yarış",
    "radio": "radyo",
    "railway": "demiryolu",
    "rain": "yağmur",
    "rainbow": "gökkuşağı",
    "reader": "okuyucu",
    "reality": "gerçeklik",
    "reason": "neden",
    "receipt": "makbuz",
    "recipe": "tarif",
    "record": "kayıt",
    "refrigerator": "buzdolabı",
    "region": "bölge",
    "relation": "ilişki",
    "relationship": "ilişki",
    "relative": "akraba",
    "religion": "din",
    "rent": "kira",
    "repair": "onarım",
    "report": "rapor",
    "reputation": "itibar",
    "research": "araştırma",
    "respect": "saygı",
    "restaurant": "restoran",
    "result": "sonuç",
    "reward": "ödül",
    "rice": "pirinç",
    "richness": "zenginlik",
    "rider": "binici",
    "ring": "yüzük",
    "risk": "risk",
    "river": "nehir",
    "road": "yol",
    "rock": "kaya",
    "role": "rol",
    "roof": "çatı",
    "room": "oda",
    "root": "kök",
    "rope": "ip",
    "row": "sıra",
    "rule": "kural",
    "ruler": "hükümdar",
    "safety": "güvenlik",
    "sailor": "denizci",
    "salary": "maaş",
    "sale": "satış",
    "salt": "tuz",
    "sand": "kum",
    "sandwich": "sandviç",
    "sauce": "sos",
    "scene": "sahne",
    "scent": "koku",
    "school": "okul",
    "science": "bilim",
    "scientist": "bilim insanı",
    "scissors": "makas",
    "screen": "ekran",
    "sea": "deniz",
    "season": "mevsim",
    "seat": "koltuk",
    "second": "saniye",
    "secret": "sır",
    "secretary": "sekreter",
    "section": "bölüm",
    "security": "güvenlik",
    "seed": "tohum",
    "seller": "satıcı",
    "sentence": "cümle",
    "service": "hizmet",
    "shadow": "gölge",
    "shame": "utanç",
    "shape": "şekil",
    "share": "pay",
    "shark": "köpekbalığı",
    "sheep": "koyun",
    "shelf": "raf",
    "ship": "gemi",
    "shirt": "gömlek",
    "shoe": "ayakkabı",
    "shop": "dükkan",
    "shore": "kıyı",
    "shoulder": "omuz",
    "shower": "duş",
    "sight": "görüş",
    "sign": "tabela",
    "silence": "sessizlik",
    "silver": "gümüş",
    "sister": "kız kardeş",
    "situation": "durum",
    "size": "boyut",
    "skill": "beceri",
    "skin": "ten",
    "skirt": "etek",
    "sky": "gökyüzü",
    "sleep": "uyku",
    "slice": "dilim",
    "smoke": "duman",
    "snake": "yılan",
    "snow": "kar",
    "soap": "sabun",
    "society": "toplum",
    "sock": "çorap",
    "sofa": "kanepe",
    "soldier": "asker",
    "solution": "çözüm",
    "son": "erkek evlat",
    "song": "şarkı",
    "soul": "ruh",
    "sound": "ses",
    "soup": "çorba",
    "source": "kaynak",
    "space": "uzay",
    "speech": "konuşma",
    "speed": "hız",
    "spirit": "ruh",
    "spoon": "kaşık",
    "sport": "spor",
    "spring": "ilkbahar",
    "square": "meydan",
    "stage": "sahne",
    "stair": "merdiven basamağı",
    "stamp": "pul",
    "star": "yıldız",
    "state": "devlet",
    "station": "istasyon",
    "statue": "heykel",
    "steak": "biftek",
    "steam": "buhar",
    "step": "adım",
    "stomach": "mide",
    "stone": "taş",
    "stop": "durak",
    "store": "mağaza",
    "storm": "fırtına",
    "story": "hikaye",
    "stranger": "yabancı",
    "street": "sokak",
    "strength": "güç",
    "student": "öğrenci",
    "studio": "stüdyo",
    "subject": "özne",
    "success": "başarı",
    "sugar": "şeker",
    "suit": "takım elbise",
    "summer": "yaz",
    "sun": "güneş",
    "supermarket": "süpermarket",
    "supper": "akşam yemeği",
    "surface": "yüzey",
    "surprise": "sürpriz",
    "sweater": "kazak",
    "sweet": "tatlı",
    "swimmer": "yüzücü",
    "sword": "kılıç",
    "system": "sistem",
    "table": "masa",
    "tail": "kuyruk",
    "talent": "yetenek",
    "target": "hedef",
    "task": "görev",
    "taste": "tat",
    "tax": "vergi",
    "taxi": "taksi",
    "tea": "çay",
    "teacher": "öğretmen",
    "team": "takım",
    "tear": "gözyaşı",
    "telephone": "telefon",
    "television": "televizyon",
    "temperature": "sıcaklık",
    "tennis": "tenis",
    "tent": "çadır",
    "term": "terim",
    "test": "test",
    "theater": "tiyatro",
    "theory": "teori",
    "thief": "hırsız",
    "thing": "şey",
    "thought": "düşünce",
    "throat": "boğaz",
    "throne": "taht",
    "ticket": "bilet",
    "time": "zaman",
    "title": "başlık",
    "toast": "tost",
    "today": "bugün",
    "toe": "ayak parmağı",
    "tomorrow": "yarın",
    "tongue": "dil",
    "tool": "alet",
    "tooth": "diş",
    "top": "üst",
    "tour": "tur",
    "tourist": "turist",
    "towel": "havlu",
    "tower": "kule",
    "town": "kasaba",
    "toy": "oyuncak",
    "track": "iz",
    "trade": "ticaret",
    "traffic": "trafik",
    "train": "tren",
    "trainer": "eğitmen",
    "transport": "ulaşım",
    "travel": "seyahat",
    "treatment": "tedavi",
    "tree": "ağaç",
    "trial": "duruşma",
    "triangle": "üçgen",
    "trip": "gezi",
    "trouble": "dert",
    "truck": "kamyon",
    "truth": "gerçek",
    "tube": "boru",
    "turkey": "hindi",
    "uncle": "amca",
    "university": "üniversite",
    "vacation": "tatil",
    "valley": "vadi",
    "value": "değer",
    "van": "kamyonet",
    "vegetable": "sebze",
    "vehicle": "araç",
    "victim": "kurban",
    "victory": "zafer",
    "video": "video",
    "view": "manzara",
    "village": "köy",
    "visitor": "ziyaretçi",
    "voice": "ses",
    "wall": "duvar",
    "war": "savaş",
    "warmth": "sıcaklık",
    "warrior": "savaşçı",
    "waste": "atık",
    "watch": "kol saati",
    "water": "su",
    "wave": "dalga",
    "way": "yol",
    "weakness": "zayıflık",
    "weapon": "silah",
    "weather": "hava",
    "wedding": "düğün",
    "week": "hafta",
    "weekend": "hafta sonu",
    "weight": "ağırlık",
    "whale": "balina",
    "wheel": "tekerlek",
    "wife": "eş",
    "wind": "rüzgar",
    "window": "pencere",
    "wine": "şarap",
    "wing": "kanat",
    "winner": "kazanan",
    "winter": "kış",
    "wire": "tel",
    "wish": "dilek",
    "wolf": "kurt",
    "woman": "kadın",
    "wood": "tahta",
    "wool": "yün",
    "word": "kelime",
    "work": "iş",
    "worker": "işçi",
    "world": "dünya",
    "worm": "solucan",
    "wound": "yara",
    "writer": "yazar",
    "writing": "yazı",
    "yard": "bahçe",
    "year": "yıl",
    "yesterday": "dün",
    "youth": "gençlik",
    "zoo": "hayvanat bahçesi"
}

# Additional high-frequency English adjectives mapped to Turkish
EXTENDED_ADJECTIVES_EN_TR = {
    "active": "aktif",
    "afraid": "korkmuş",
    "alive": "canlı",
    "alone": "yalnız",
    "angry": "kızgın",
    "anxious": "kaygılı",
    "asleep": "uykuda",
    "attractive": "çekici",
    "automatic": "otomatik",
    "awake": "uyanık",
    "aware": "farkında",
    "awesome": "harika",
    "basic": "temel",
    "bitter": "acı",
    "blind": "kör",
    "bold": "cesur",
    "boring": "sıkıcı",
    "brave": "cesur",
    "bright": "parlak",
    "busy": "meşgul",
    "calm": "sakin",
    "careful": "dikkatli",
    "careless": "dikkatsiz",
    "certain": "kesin",
    "cheap": "ucuz",
    "clean": "temiz",
    "clear": "açık",
    "clever": "akıllı",
    "cold": "soğuk",
    "colorful": "renkli",
    "common": "yaygın",
    "cool": "serin",
    "correct": "doğru",
    "crazy": "çılgın",
    "cruel": "zalim",
    "curious": "meraklı",
    "dangerous": "tehlikeli",
    "dark": "karanlık",
    "dead": "ölü",
    "deaf": "sağır",
    "deep": "derin",
    "delicious": "lezzetli",
    "different": "farklı",
    "difficult": "zor",
    "dirty": "kirli",
    "dry": "kuru",
    "early": "erken",
    "easy": "kolay",
    "empty": "boş",
    "energetic": "enerjik",
    "equal": "eşit",
    "exact": "tam",
    "excited": "heyecanlı",
    "expensive": "pahalı",
    "fair": "adil",
    "fake": "sahte",
    "false": "yanlış",
    "famous": "ünlü",
    "far": "uzak",
    "fast": "hızlı",
    "fat": "şişman",
    "final": "son",
    "foolish": "aptalca",
    "foreign": "yabancı",
    "free": "özgür",
    "fresh": "taze",
    "full": "dolu",
    "funny": "komik",
    "general": "genel",
    "generous": "cömert",
    "gentle": "nazik",
    "glad": "memnun",
    "global": "küresel",
    "good": "iyi",
    "great": "harika",
    "greedy": "açgözlü",
    "guilty": "suçlu",
    "happy": "mutlu",
    "hard": "zor",
    "healthy": "sağlıklı",
    "heavy": "ağır",
    "helpful": "yardımsever",
    "high": "yüksek",
    "honest": "dürüst",
    "hopeless": "umutsuz",
    "hot": "sıcak",
    "huge": "kocaman",
    "hungry": "aç",
    "ill": "hasta",
    "important": "önemli",
    "impossible": "imkansız",
    "innocent": "masum",
    "intelligent": "zeki",
    "interesting": "ilginç",
    "jealous": "kıskanç",
    "kind": "nazik",
    "late": "geç",
    "lazy": "tembel",
    "light": "hafif",
    "little": "küçük",
    "lonely": "yalnız",
    "long": "uzun",
    "loud": "gürültülü",
    "lovely": "sevimli",
    "low": "alçak",
    "lucky": "şanslı",
    "mad": "deli",
    "modern": "modern",
    "narrow": "dar",
    "natural": "doğal",
    "near": "yakın",
    "necessary": "gerekli",
    "nervous": "gergin",
    "new": "yeni",
    "nice": "güzel",
    "noisy": "gürültülü",
    "normal": "normal",
    "odd": "tuhaf",
    "old": "eski",
    "open": "açık",
    "painful": "acılı",
    "pale": "soluk",
    "patient": "sabırlı",
    "peaceful": "huzurlu",
    "perfect": "kusursuz",
    "pleasant": "hoş",
    "polite": "kibar",
    "poor": "yoksul",
    "popular": "popüler",
    "possible": "mümkün",
    "powerful": "güçlü",
    "precious": "değerli",
    "pretty": "güzel",
    "proud": "gururlu",
    "pure": "saf",
    "quick": "çabuk",
    "quiet": "sessiz",
    "rare": "nadir",
    "ready": "hazır",
    "real": "gerçek",
    "rich": "zengin",
    "right": "doğru",
    "rough": "pürüzlü",
    "round": "yuvarlak",
    "rude": "kaba",
    "sad": "üzgün",
    "safe": "güvenli",
    "salty": "tuzlu",
    "scared": "korkmuş",
    "secret": "gizli",
    "serious": "ciddi",
    "shallow": "sığ",
    "sharp": "keskin",
    "short": "kısa",
    "shy": "utangaç",
    "sick": "hasta",
    "silent": "sessiz",
    "simple": "basit",
    "slow": "yavaş",
    "small": "küçük",
    "smart": "akıllı",
    "smooth": "pürüzsüz",
    "soft": "yumuşak",
    "sour": "ekşi",
    "special": "özel",
    "strange": "garip",
    "strong": "güçlü",
    "stupid": "aptal",
    "successful": "başarılı",
    "sweet": "tatlı",
    "tall": "uzun boylu",
    "terrible": "korkunç",
    "thick": "kalın",
    "thin": "ince",
    "thirsty": "susamış",
    "tight": "sıkı",
    "tiny": "küçücük",
    "tired": "yorgun",
    "true": "doğru",
    "ugly": "çirkin",
    "unique": "benzersiz",
    "unusual": "olağandışı",
    "useful": "faydalı",
    "useless": "faydasız",
    "valuable": "değerli",
    "warm": "ılık",
    "weak": "zayıf",
    "wealthy": "varlıklı",
    "wet": "ıslak",
    "wide": "geniş",
    "wild": "vahşi",
    "wise": "bilge",
    "wonderful": "harika",
    "wrong": "yanlış",
    "young": "genç"
}


# ==============================================================================
# 3. QUESTION PATTERNS & IMPERATIVES
# ==============================================================================

QUESTION_STARTERS_EN = {
    "what": "ne",
    "where": "nerede",
    "when": "ne zaman",
    "why": "neden",
    "who": "kim",
    "how": "nasıl",
    "which": "hangi",
    "whose": "kimin"
}

QUESTION_STARTERS_TR = {
    "ne": "what",
    "nerede": "where",
    "nereye": "where",
    "nereden": "where from",
    "ne zaman": "when",
    "neden": "why",
    "niye": "why",
    "niçin": "why",
    "kim": "who",
    "kime": "to whom",
    "nasıl": "how",
    "hangi": "which",
    "kaç": "how many",
    "ne kadar": "how much"
}


# ==============================================================================
# 4. FULL TURKISH PRONOUN INFLECTION & TRANSITIVITY MAP
# ==============================================================================

TURKISH_PRONOUNS_FULL = {
    # Nominative (Yalın)
    "ben": {"en": "I", "role": "subject", "person": "1s", "case": "nominative"},
    "sen": {"en": "you", "role": "subject", "person": "2s", "case": "nominative"},
    "o": {"en": "he", "role": "subject", "person": "3s", "case": "nominative"},
    "biz": {"en": "we", "role": "subject", "person": "1p", "case": "nominative"},
    "siz": {"en": "you", "role": "subject", "person": "2p", "case": "nominative"},
    "onlar": {"en": "they", "role": "subject", "person": "3p", "case": "nominative"},

    # Accusative (-i hali)
    "beni": {"en": "me", "role": "object", "person": "1s", "case": "accusative"},
    "seni": {"en": "you", "role": "object", "person": "2s", "case": "accusative"},
    "onu": {"en": "him", "role": "object", "person": "3s", "case": "accusative"},
    "bizi": {"en": "us", "role": "object", "person": "1p", "case": "accusative"},
    "sizi": {"en": "you", "role": "object", "person": "2p", "case": "accusative"},
    "onları": {"en": "them", "role": "object", "person": "3p", "case": "accusative"},

    # Dative (-e hali)
    # Direct object 'me' for verbs like answer/help/tell/ask, otherwise 'to me'
    "bana": {"en": "me", "prep_en": "to me", "role": "object", "person": "1s", "case": "dative"},
    "sana": {"en": "you", "prep_en": "to you", "role": "object", "person": "2s", "case": "dative"},
    "ona": {"en": "him", "prep_en": "to him", "role": "object", "person": "3s", "case": "dative"},
    "bize": {"en": "us", "prep_en": "to us", "role": "object", "person": "1p", "case": "dative"},
    "size": {"en": "you", "prep_en": "to you", "role": "object", "person": "2p", "case": "dative"},
    "onlara": {"en": "them", "prep_en": "to them", "role": "object", "person": "3p", "case": "dative"},

    # Locative (-de hali)
    "bende": {"en": "with me", "prep_en": "on me", "role": "adverbial", "person": "1s", "case": "locative"},
    "sende": {"en": "with you", "prep_en": "on you", "role": "adverbial", "person": "2s", "case": "locative"},
    "onda": {"en": "with him", "prep_en": "in him", "role": "adverbial", "person": "3s", "case": "locative"},
    "bizde": {"en": "with us", "prep_en": "at our place", "role": "adverbial", "person": "1p", "case": "locative"},
    "sizde": {"en": "with you", "prep_en": "at your place", "role": "adverbial", "person": "2p", "case": "locative"},
    "onlarda": {"en": "with them", "prep_en": "in them", "role": "adverbial", "person": "3p", "case": "locative"},

    # Ablative (-den hali)
    "benden": {"en": "from me", "prep_en": "from me", "role": "adverbial", "person": "1s", "case": "ablative"},
    "senden": {"en": "from you", "prep_en": "from you", "role": "adverbial", "person": "2s", "case": "ablative"},
    "ondan": {"en": "from him", "prep_en": "from him", "role": "adverbial", "person": "3s", "case": "ablative"},
    "bizden": {"en": "from us", "prep_en": "from us", "role": "adverbial", "person": "1p", "case": "ablative"},
    "sizden": {"en": "from you", "prep_en": "from you", "role": "adverbial", "person": "2p", "case": "ablative"},
    "onlardan": {"en": "from them", "prep_en": "from them", "role": "adverbial", "person": "3p", "case": "ablative"},

    # Instrumental (ile)
    "benimle": {"en": "with me", "prep_en": "with me", "role": "adverbial", "person": "1s", "case": "instrumental"},
    "seninle": {"en": "with you", "prep_en": "with you", "role": "adverbial", "person": "2s", "case": "instrumental"},
    "onunla": {"en": "with him", "prep_en": "with him", "role": "adverbial", "person": "3s", "case": "instrumental"},
    "bizimle": {"en": "with us", "prep_en": "with us", "role": "adverbial", "person": "1p", "case": "instrumental"},
    "sizinle": {"en": "with you", "prep_en": "with you", "role": "adverbial", "person": "2p", "case": "instrumental"},
    "onlarla": {"en": "with them", "prep_en": "with them", "role": "adverbial", "person": "3p", "case": "instrumental"},

    # Genitive (İyelik)
    "benim": {"en": "my", "role": "possessive", "person": "1s", "case": "genitive"},
    "senin": {"en": "your", "role": "possessive", "person": "2s", "case": "genitive"},
    "onun": {"en": "his", "role": "possessive", "person": "3s", "case": "genitive"},
    "bizim": {"en": "our", "role": "possessive", "person": "1p", "case": "genitive"},
    "sizin": {"en": "your", "role": "possessive", "person": "2p", "case": "genitive"},
    "onların": {"en": "their", "role": "possessive", "person": "3p", "case": "genitive"},
}


# ==============================================================================
# 5. TURKISH COMPOUND VERBS (BİRLEŞİK FİİLLER: İsim + Yardımcı Fiil)
# ==============================================================================

TURKISH_COMPOUND_VERBS = {
    # noun -> {aux_root: (en_verb, is_transitive_to_dative)}
    "cevap": {"ver": ("answer", True), "verme": ("not answer", True)},
    "yanıt": {"ver": ("answer", True), "verme": ("not answer", True)},
    "yardım": {"et": ("help", True), "etme": ("not help", True), "ol": ("help", True)},
    "teşekkür": {"et": ("thank", True), "etme": ("not thank", True)},
    "özür": {"dile": ("apologize", False)},
    "karar": {"ver": ("decide", False)},
    "izin": {"ver": ("allow", True)},
    "fark": {"et": ("notice", True)},
    "telefon": {"et": ("call", True)},
    "merak": {"et": ("worry", False)},
    "dua": {"et": ("pray", False)},
    "dikkat": {"et": ("be careful", False)},
    "takip": {"et": ("follow", True)},
    "kabul": {"et": ("accept", True)},
    "red": {"et": ("reject", True)},
    "sohbet": {"et": ("chat", False)},
    "ziyaret": {"et": ("visit", True)},
    "devam": {"et": ("continue", False)},
    "kontrol": {"et": ("check", True)},
    "tercih": {"et": ("prefer", True)},
    "tahmin": {"et": ("guess", True)},
    "şikayet": {"et": ("complain", False)},
    "söz": {"ver": ("promise", True)},
    "itiraf": {"et": ("admit", True)},
    "hata": {"yap": ("make a mistake", False)},
    "pes": {"et": ("give up", False)}
}


# ==============================================================================
# 6. CONVERSATIONAL EVERYDAY EXPRESSIONS & IDIOMS (TR -> EN)
# ==============================================================================

TURKISH_CONVERSATIONAL_EXPRESSIONS = {
    "nasılsın": "How are you?",
    "nasılsınız": "How are you?",
    "ne haber": "What's up?",
    "naber": "What's up?",
    "iyiyim": "I am good.",
    "çok iyiyim": "I am very good.",
    "teşekkür ederim": "Thank you.",
    "teşekkürler": "Thank you.",
    "çok teşekkürler": "Thank you very much.",
    "sağ ol": "Thank you.",
    "sağol": "Thank you.",
    "bir şey değil": "You're welcome.",
    "rica ederim": "You're welcome.",
    "kendine iyi bak": "Take care of yourself.",
    "hoşça kal": "Goodbye.",
    "hoşçakal": "Goodbye.",
    "görüşürüz": "See you later.",
    "günaydın": "Good morning.",
    "iyi akşamlar": "Good evening.",
    "iyi geceler": "Good night.",
    "kolay gelsin": "Take it easy.",
    "afiyet olsun": "Enjoy your meal.",
    "geçmiş olsun": "Get well soon.",
    "özür dilerim": "I am sorry.",
    "lütfen": "Please.",
    "tamam": "Okay.",
    "tabii ki": "Of course.",
    "elbette": "Of course.",
    "fark etmez": "It doesn't matter.",
    "ne yapıyorsun": "What are you doing?",
    "ne yapıyosun": "What are you doing?",
    "neredesin": "Where are you?",
    "iyi şanslar": "Good luck.",
    "bol şans": "Good luck.",
    "hoş geldin": "Welcome.",
    "hoş geldiniz": "Welcome.",
    "hoşgeldin": "Welcome.",
    "hoşgeldiniz": "Welcome.",
    "seni seviyorum": "I love you.",
    "seni çok seviyorum": "I love you very much.",
    "seni özledim": "I miss you.",
    "yardım edin": "Help!",
    "yardım et": "Help me.",
    "imdat": "Help!",
    "ne demek": "You're welcome.",
    "merhaba": "Hello.",
    "selam": "Hi."
}


# ==============================================================================
# 7. TURKISH IMPERATIVE & REQUEST STEMS
# ==============================================================================

TURKISH_IMPERATIVE_STEMS = {
    "ver": "give",
    "yap": "do",
    "git": "go",
    "gel": "come",
    "bak": "look",
    "dinle": "listen",
    "söyle": "say",
    "otur": "sit",
    "kalk": "stand up",
    "dur": "stop",
    "oku": "read",
    "yaz": "write",
    "konuş": "speak",
    "ye": "eat",
    "iç": "drink",
    "al": "take",
    "bırak": "leave",
    "bekle": "wait",
    "aç": "open",
    "kapa": "close",
    "kapat": "close",
    "sus": "shut up",
    "yardım": "help"
}

